### ISSUE TITLE
Crisper support?

### ISSUE THREAD

**Issue by alex88** [mbykovskyy/broccoli-vulcanize#5]
Is there a way to use crisper for the old `csp` option? I think the logic should be added in this plugin as in https://github.com/PolymerLabs/crisper#usage-with-vulcanize

**Comment by mbykovskyy** [comment]
I think `crisper` should be a separate plugin. It used to be part of `vulcanize` but they extracted it out for whatever reasons so I don't think it's a good idea to mix both in the same plugin.

**Comment by awgeorge** [comment]
'They' have included it in their grunt plugin.... https://github.com/Polymer/grunt-vulcanize#optionscsp

**Comment by mbykovskyy** [comment]
There are many reasons why I don't want to add `crisper` to this plugin.

- If it's not in `vulcanize` it shouldn't be in this plugin. `broccoli-vulcanize` was designed to be a mere wrapper of `vulcanize` to make it work with `broccoli` pipeline.
- If they keep adding and removing features is this plugin meant to support features that are no longer supported? I personally don't think it should.
- Separation of concerns. `crisper` can be applied to any `html` file not just vulcanized `html` so it makes sense to create a `broccoli-crisper` plugin, in fact they are asking for somebody to implement it in their `crisper` readme. Unfortunately, I'm not working with `polymer` or `broccoli` at the moment so I don't have time to write it.
- They are also asking somebody to implement `grunt-crisper` and I have a feeling that once it's implemented they are going to remove `csp` support from their `grunt-vulcanze`. They've already done it to `strip` flag, which makes sense. I never used `strip` flag because I used `broccoli-htmlmin`.
